M48
; DRILL file {KiCad (6.0.5)} date Sun Aug 14 01:36:21 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-14T01:36:21-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.5817Y-0.7098
X2.7726Y-0.7098
T2
X2.5699Y-0.5906
X2.7844Y-0.5906
T0
M30
