M48
; DRILL file {KiCad (6.0.5)} date Fri Aug  5 12:45:16 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-05T12:45:16-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X2.1093Y-0.8673
X2.3002Y-0.8673
T2
X2.0974Y-0.748
X2.312Y-0.748
T0
M30
